const ADD_TODO_ITEM = "ADD_TODO_ITEM";
const CHANGE_TODO_STATUS = "CHANGE_TODO_STATUS";
const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
const FETCHING_DATA = "FETCHING_DATA";
const FETCH_DATA_SUCCESES = "FETCH_DATA_SUCCESES";
const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESSES = "LOGIN_SUCCESSES";
const LOGIN_ERROR = "LOGIN_ERROR";
const LOGUP_REQUEST = "LOGUP_REQUEST";
const LOGUP_SUCCESSES = "LOGUP_SUCCESSES";
const LOGUP_ERROR = "LOGUP_ERROR";

export {
  ADD_TODO_ITEM,
  CHANGE_TODO_STATUS,
  DELETE_TODO_ITEM,
  FETCHING_DATA,
  FETCH_DATA_SUCCESES,
  FETCH_DATA_ERROR,
  LOGIN_REQUEST,
  LOGIN_SUCCESSES,
  LOGIN_ERROR,
  LOGUP_REQUEST,
  LOGUP_SUCCESSES,
  LOGUP_ERROR
};
