const ADD_TODO_ITEM = "ADD_TODO_ITEM";
const CHANGE_TODO_STATUS = "CHANGE_TODO_STATUS";
const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
const FETCHING_DATA = "FETCHING_DATA";
const FETCH_DATA_SUCCESES = "FETCH_DATA_SUCCESES";
const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";

export { 
    ADD_TODO_ITEM, 
    CHANGE_TODO_STATUS, 
    DELETE_TODO_ITEM,
    FETCHING_DATA,
    FETCH_DATA_SUCCESES,
    FETCH_DATA_ERROR
};
