export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const CHANGE_TODO_STATUS = "CHANGE_TODO_STATUS";
export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
export const FETCHING_DATA = "FETCHING_DATA";
export const FETCH_DATA_SUCCESES = "FETCH_DATA_SUCCESES";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESSES = "LOGIN_SUCCESSES";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGUP_REQUEST = "LOGUP_REQUEST";
export const LOGUP_SUCCESSES = "LOGUP_SUCCESSES";
export const LOGUP_ERROR = "LOGUP_ERROR";
export const VEREFICATE_REQUEST = "VEREFICATE_REQUEST";
export const VEREFICATE_SUCCESSES = "VEREFICATE_SUCCESSES";
export const VEREFICATE_ERROR = "VEREFICATE_ERROR";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESSES = "LOGOUT_SUCCESSES";
export const LOGOUT_ERROR = "LOGOUT_ERROR";



